= Modules, Endpoints, SQL, GCS, new Channel impl, … aka new CapeDwarf 1.0.0.Beta6
alesj
2013-09-11
:revdate: 2013-09-11 15:44:00 +0100
:awestruct-tags: [announcement, release]
:awestruct-layout: news
:source-highlighter: coderay

As you can see from the title, and from a bit late release, we’ve again been very busy.

- http://downloads.jboss.org/capedwarf/CapeDwarf_AS7_1.0.0.Beta6.zip[CapeDwarf 1.0.0.Beta6]

- https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12311321&version=12318736[Release Notes]

Let’s just go over all new features.

== Modules

- https://developers.google.com/appengine/docs/java/modules/[Modules spec]

There is a bit of limitation on our end here, as there is no (easy / nice) dynamic way (to my knowledge) to scale up / down virtual servers (at runtime during deployment phase) in JBossWeb that comes with JBossAS7 (which is what we use). In order to use Modules with CapeDwarf, you must use “standalone-capedwarf-modules.xml” configuration when you startup CapeDwarf AS instance.

You must also configure the number of virtual servers to match your application’s modularization. See web subsystem configuration in “standalone-capedwarf-modules.xml” for more details.

(or simply ping me for any Modules questions - via forums, email, Twitter or Freenode IRC #capedwarf)

- https://github.com/GoogleCloudPlatform/appengine-tck/tree/master/core/modules[Modules TCK tests]

== Endpoints

- https://developers.google.com/appengine/docs/java/endpoints/[Endpoints spec]

We’ve managed to map GAE’s Endpoints annotations to JAXRS/RestEasy annotations, and 
we also support custom serialization.

In our case / implementation we only need .api files as markers, and not to read any information from it -- you can have a single .api dummy file if you like.

- https://github.com/GoogleCloudPlatform/appengine-tck/tree/master/core/endpoints[Endpoints TCK tests]

== SQL

SQL was of course supported out-of-the-box for us.
We we just had to hack GAE’s Driver class to connect against selected DataSource:

- https://github.com/capedwarf/capedwarf-blue/blob/master/sql/src/main/java/org/jboss/capedwarf/sql/JndiDataSource.java[DataSource lookup]

- https://github.com/GoogleCloudPlatform/appengine-tck/tree/master/core/sql[SQL TCK tests]

== GCS

FileService is being deprecated in favor of Google Cloud Storage (GCS) API. At the moment dev / local implementation of the GCS client library still goes against FileService implementation, so supporting this was easy, as we already fully implemented FileService API.

- https://github.com/GoogleCloudPlatform/appengine-tck/tree/master/ext/gcs-client[GCS TCK tests]

== Channel

We re-implemented Channel API.

Big thanks to https://github.com/chrisritter[@chrisritter] for kicking our butt to do this, and contributing a simple but cool chat app for testing purposes: https://github.com/chrisritter/simplechat[SimpleChat].

Also thanks to https://github.com/kpiwko[Karel] for stepping up and fixing Arquillian Drone so we can finally automagically test this.

- https://github.com/GoogleCloudPlatform/appengine-tck/tree/master/tests/appengine-tck-channel[Channel TCK tests]

== JavaOne 2013

Don’t miss my presentation at JavaOne -- Tuesday 24th September at 11:30am, Parc55. 

- https://oracleus.activeevents.com/2013/connect/sessionDetail.ww?SESSION_ID=2117[Implementing Your Own Google App Engine]

Or my previously mentioned DC JBUG talk: http://www.meetup.com/DC-JBug/events/128068042/

== Blogs

https://twitter.com/myfear[Markus Eisele] posted a nice overview of CapeDwarf:

- http://blog.eisele.net/2013/09/capedwarf-google-app-engine-on-java-ee.html[CapeDwarf - Google App Engine on Java EE]


Anyway, enjoy the new release! Feedback welcome as always.


