# Default page title
title: CapeDwarf

# Project id name
project: capedwarf

# Default minify settings
css_minifier: disabled
js_minifier: disabled
html_minifier: disabled

# Merge multiple JavaScript files to improve performance
fileMerger:
  enabled: true
  outputFilePath: /javascripts/bootstrap-community.js
  paths:
    - /javascripts/_bootstrap-transition.js
    - /javascripts/_bootstrap-alert.js
    - /javascripts/_bootstrap-button.js
    - /javascripts/_bootstrap-carousel.js
    - /javascripts/_bootstrap-collapse.js
    - /javascripts/_bootstrap-dropdown.js
    - /javascripts/_bootstrap-modal.js
    - /javascripts/_bootstrap-tooltip.js
    - /javascripts/_bootstrap-popover.js
    - /javascripts/_bootstrap-scrollspy.js
    - /javascripts/_bootstrap-tab.js
    - /javascripts/_bootstrap-typeahead.js
    - /javascripts/_bootstrap-affix.js
    - /javascripts/_jbossorg-navbarfix.js
    - /javascripts/_jquery-easytabs.js
    - /javascripts/_crisp-scripts.js
    - /javascripts/_jbossorg-tabzilla.js

# Cache hosted fonts, images and javascript
wget:
  enabled: true
  rerunEach: 86400 # seconds
  timestampFilename: _wget-timestamp
  options:
    - --no-remove-listing
    - -q
    - -r
    - --no-parent
    - -N
    - --reject 'index.html*'
    - -e robots=off
    - --directory-prefix=cache
  urls:
    - http://static.jboss.org/theme/js/libs/jquery/jquery-1.9.1.js
    - http://static.jboss.org/theme/js/libs/jquery/jquery-1.9.1.min.js
    - http://static.jboss.org/theme/js/libs/html5/pre3.6/html5.min.js
    - http://static.jboss.org/theme/js/libs/prettify/188.0.0/prettify.min.js
    - http://static.jboss.org/theme/js/libs/holder/1.9/holder.js
    - http://static.jboss.org/theme/fonts/titilliumtext/
    - http://static.jboss.org/theme/fonts/font-awesome/
    - http://static.jboss.org/theme/images/common/
    - http://static.jboss.org/example/
    - http://www.jboss.org/dms/capedwarf/images/capedwarf-banner-1180px.png


####################################################################################################
# Asciidoctor config
####################################################################################################
asciidoctor:
  :safe: safe
  :attributes:
    #sitename: WriteAdapt
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    toclevels: 3
    icons: font
    source-highlighter: coderay
    coderay-css: style

# Update resource URLs based on the profile
profiles:
  development:
    jborg_fonts_url: /cache/static.jboss.org/theme/fonts
    jborg_images_url: /cache/static.jboss.org/theme/images
    jborg_js_url: /cache/static.jboss.org/theme/js
    project_images_url: /cache/www.jboss.org/dms/capedwarf/images
    bootstrap_css_url: /stylesheets-source/_bootstrap-community
    bootstrap_js_url: /javascripts/bootstrap-community
    symlinker:
      from: ../stylesheets
      to: ./_site/stylesheets-source
    asciidoctor:
      :attributes:
        base_url: http://localhost:4242
        imagesdir: /images
  staging:
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: http://www.jboss.org/dms/capedwarf/images/
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/2.3.1.1/bootstrap-community
    bootstrap_js_url: http://static.jboss.org/capedwarf/scripts/bootstrap-community
    base_url: http://capedwarf.org/staging
    wget:
      enabled: false
    asciidoctor:
      :attributes:
        base_url: http://capedwarf.org/staging
        imagesdir: /staging/images
  production:
    minified: .min
    css_minifier: enabled
    js_minifier: enabled
    html_minifier: enabled
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: http://www.jboss.org/dms/capedwarf/images/
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/2.3.1.1/bootstrap-community
    bootstrap_js_url: http://static.jboss.org/capedwarf/scripts/bootstrap-community
    base_url: http://capedwarf.org
    wget:
      enabled: false
    asciidoctor:
      :attributes:
        base_url: http://capedwarf.org
        imagesdir: /images
